services:
  - type: web
    name: real-time-forum
    runtime: image
    image:
      url: docker.io/saabdulla/real-time-forum:latest
    plan: free
    region: frankfurt
    envVars:
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /
    autoDeploy: false